### ISSUE TITLE
README doesn't mention requirement to clone submodule

### ISSUE THREAD

**Issue by pief** [fabianishere/boot2flappy#2]
```
git submodule init
git submodule update
```

is needed when cloning the repo, even when building with Docker.

**Comment by fabianishere** [comment]
Ah, I had not thought about that. Is #3 clear enough?

**Comment by pief** [comment]
Yes, perfect!

One more thing I just noticed: after building with docker, the `build/` directory tree might have the wrong permissions being owned by `root`. I needed to `chown -R` in order to run `build/vm/start.sh`.

Thanks for coding this BTW, and in case you were wondering why for God's sake someone else would use it: I currently use it to debug UEFI booting from the local EFI partition vs. UEFI pxe boot. Unfortunately I can't even get boot2flappy to boot from the local EFI partition on my Dell PowerEdge R740 server here (yes, there are insane people booting EFI games on servers ;): "Not Found (14)". No permissions in place on a FAT filesystem, so it can't be that.

**Comment by fabianishere** [comment]
@pief  Hmm, I don't think we can fix that, given that Docker runs as root user. Though, we can still document it.

Very interesting use-case! :P 
For my information, does it print the welcome message before the Not Found error (That is, "Welcome to Flappy Bird!")? In that case, it looks like it couldn't find the sprites on the filesystem.

**Comment by pief** [comment]
Yes, documenting it is enough.

Fixed it: what did not work was creating a directory `EFI/boot2flappy` and placing `BOOTX64.EFI` and `SPRITES.BMP` there. Once I copied both files to `EFI/boot` (with `BOOTX64.EFI` renamed to `boot2flappy.efi` so I don't overwrite my actual bootloader...) it booted like a charm. Thanks again.

**Comment by fabianishere** [comment]
Great to hear! Does the game actually run on the PowerEdge? I did not always reliably work on real hardware for me.

**Comment by pief** [comment]
See for yourself -- the next big (as in big iron) gaming platform ;) https://youtu.be/KsYmklvE6aQ

**Comment by pief** [comment]
One more note: unfortunately it doesn't support PXE booting -- fails at "Obtain root directory of file system" with "WAIT". And no, I do not expect you to implement PXE support ;) Have a great day!

**Comment by fabianishere** [comment]
Never would have expected it to run on a server :)
Have a great day too!
